# Generated by Django 5.1.4 on 2025-01-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_alter_student_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('f_color', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Marks',
        ),
    ]
